# Generated by Django 3.2.19 on 2023-05-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memarathi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
