# Generated by Django 3.2.19 on 2023-05-17 20:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('author_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='known_for',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
        migrations.AddField(
            model_name='destination',
            name='destination_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='best_time',
            field=models.CharField(max_length=100, verbose_name='Best time(Season/Month)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='blog.Destination'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ideal_duration',
            field=models.CharField(max_length=200, verbose_name='Ideal trip duration (days)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
